# Generated by Django 4.1.2 on 2022-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_notifications_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.BooleanField(),
        ),
    ]
