# Generated by Django 4.1.2 on 2022-12-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_controlpoint_camera_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
