# Generated by Django 4.1.2 on 2022-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_delete_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(null=True, upload_to='workers_images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
