# Generated by Django 4.1.2 on 2022-12-12 07:25

from django.db import migrations, models
import workers.models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_worker_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(null=True, upload_to=workers.models.worker_photo_directory_path),
        ),
    ]
