# Generated by Django 4.1.2 on 2022-12-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_rename_controlpointid_controllist_controlpoint_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controllist',
            unique_together={('worker', 'controlPoint')},
        ),
    ]
