# Generated by Django 4.1.2 on 2022-12-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_alter_controllist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlpoint',
            name='workers',
        ),
        migrations.DeleteModel(
            name='ControlList',
        ),
    ]
