# Generated by Django 4.1.2 on 2022-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_remove_controlpoint_workers_delete_controllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='workers',
            field=models.ManyToManyField(to='workers.worker'),
        ),
    ]
