# Generated by Django 4.1.2 on 2022-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_controlpoint_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to='workers.worker'),
        ),
    ]
