# Generated by Django 4.1.2 on 2022-12-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
