# Generated by Django 4.1.2 on 2022-12-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitjuornal',
            name='fixedPhotoID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.photobase'),
        ),
    ]
