# Generated by Django 4.1.2 on 2022-12-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_alter_visitjuornal_fixedphotoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitjuornal',
            name='fixedPhotoID',
        ),
    ]
