# Generated by Django 4.1.2 on 2022-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_remove_visitjuornal_fixedphotoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitjuornal',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitjuornal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
