# Generated by Django 4.1.2 on 2022-12-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_visitjuornal_time_alter_visitjuornal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='workers',
            field=models.ManyToManyField(null=True, related_name='controlPoints', to='workers.worker'),
        ),
    ]
