# Generated by Django 4.1.2 on 2022-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0020_alter_controlpoint_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='controlPoints', to='workers.worker'),
        ),
    ]
