# Generated by Django 4.1.2 on 2022-12-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0022_alter_notifications_userid_alter_report_authid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
