# Generated by Django 4.1.2 on 2022-12-15 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0023_remove_notifications_userid_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='sendTypeID',
        ),
        migrations.AddField(
            model_name='notifications',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='eventTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.eventtype'),
        ),
    ]
