# Generated by Django 4.1.2 on 2022-12-15 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0024_remove_notifications_sendtypeid_notifications_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='eventTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.visittype'),
        ),
    ]
