# Generated by Django 4.1.2 on 2022-12-15 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0025_alter_notifications_eventtypeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='eventTypeID',
            new_name='visitType',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together={('userID', 'visitType')},
        ),
    ]
