# Generated by Django 4.1.2 on 2022-12-15 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0026_rename_eventtypeid_notifications_visittype_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notifications',
            name='eventType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.eventtype'),
        ),
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together={('userID', 'eventType')},
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='visitType',
        ),
    ]
