# Generated by Django 4.1.2 on 2022-12-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0027_alter_notifications_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittype',
            name='visitTypeName',
            field=models.CharField(max_length=40),
        ),
    ]
