# Generated by Django 4.1.2 on 2022-12-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0028_alter_visittype_visittypename'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='controlPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.controlpoint'),
        ),
    ]
