# Generated by Django 4.1.2 on 2022-12-16 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0029_notifications_controlpoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together={('userID', 'eventType', 'controlPoint')},
        ),
    ]
