# Generated by Django 4.1.2 on 2023-02-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0030_alter_notifications_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='departmentID',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='positionID',
            new_name='position',
        ),
    ]
