# Generated by Django 4.1.2 on 2023-02-07 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0031_rename_departmentid_worker_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='visitjuornal',
            old_name='controlPointID',
            new_name='controlPoint',
        ),
        migrations.RenameField(
            model_name='visitjuornal',
            old_name='personID',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='visitjuornal',
            old_name='visitTypeID',
            new_name='visitType',
        ),
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together={('user', 'eventType', 'controlPoint')},
        ),
    ]
